#!/bin/bash

name="jclftp"  #Name of command to run script

#This script will be added to the home bin folder to run
#the program
read -r -d '' script <<-EOF
#!/bin/bash
#This script is automatically generated by
#the install.sh file in the jcl_ftp folder
dir="$PWD"               #Path to script
exe="\$dir/jcl_ftp.sh"   #Executable script
#Check for directory of actual script
if [ -d "\$dir" ]; then
     #Check if script exists
     if [ -f "\$exe" ]; then
          #Run script
          exec \$exe
     else
          echo "ERROR: Could not find jcl_ftp.sh executable"
     fi
else
     echo "ERROR: Could not find jcl_ftp folder"
fi
EOF

#Check for home/bin
echo "Checking if HOME/bin directory exists"
sleep .5
if [ ! -d "$HOME/bin" ] ; then
     echo "Creating bin in home directory"
     sleep .5
     mkdir "$HOME/bin"
fi

#Create executable
echo "Installing executable in home bin."
sleep .5
echo "$script" > "$HOME/bin/$name"      #Create script, overwriting previous files with the same name
chmod u+x "$HOME/bin/$name"             #Give executable perm. to user
echo -e "Script has been added. Type \"$name\" to run application."
sleep .5

